- name: Deploy Songtor App to EC2
  hosts: aws_ec2
  become: yes
  vars:
    ansible_ssh_private_key_file: "./songtor-key.pem"
    ansible_user: ec2-user
  
  tasks:
    - name: Install Docker
      dnf:
        name: docker
        state: present

    - name: Ensure /usr/local/lib/docker/cli-plugins exists
      file:
        path: /usr/local/lib/docker/cli-plugins
        state: directory
        mode: '0755'

    - name: Install Docker Compose CLI Plugin manually
      get_url:
        url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
        dest: /usr/local/lib/docker/cli-plugins/docker-compose
        mode: '0755'
        
    - name: Install Docker Buildx plugin manually
      get_url:
        url: https://github.com/docker/buildx/releases/download/v0.17.1/buildx-v0.17.1.linux-amd64
        dest: /usr/local/lib/docker/cli-plugins/docker-buildx
        mode: '0755'

    - name: Verify Docker Buildx installation
      shell: docker buildx version
      register: buildx_v
    
    - debug:
        var: buildx_v.stdout

    - name: Start and Enable Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create App Directory
      file:
        path: /home/ec2-user/app
        state: directory
        owner: ec2-user

    - name: Copy Code and Docker Compose
      copy:
        src: ../../
        dest: /home/ec2-user/app/
        owner: ec2-user

    - name: Run Docker Compose
      shell:
        cmd: docker compose up -d --build
        chdir: /home/ec2-user/app/deployments